name: lint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  precious:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.42"
      - uses: oalders/install-ubi-action@v0.0.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          projects: |
            houseabsolute/precious
            houseabsolute/omegasort
      - uses: perl-actions/install-with-cpm@v2
        with:
          install: |
            App::perlvars
            Perl::Tidy
          sudo: false
      - run: precious lint --all
